services:
  app:
    image: todo-frontend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/home/node/app
    ports:
      - 5173:5173
    container_name: todo-frontend-dev
